# Generated by Django 2.2.6 on 2019-11-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycharacter',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitycharacter',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitygenre',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitygenre',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityorganity',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityorganity',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityproduction',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityproduction',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityshow',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityshow',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityurl',
            name='href',
            field=models.URLField(help_text='Enter the url'),
        ),
        migrations.AlterField(
            model_name='entityurl',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityurl',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitywork',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitywork',
            name='sort_name',
            field=models.CharField(help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharactercharactertype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharactercharactertype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharactergenretype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharactergenretype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharacterurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharacterurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationgenregenretype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationgenregenretype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationgenreurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationgenreurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganitycharactertype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganitycharactertype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganitygenretype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganitygenretype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityorganitytype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityorganitytype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityworktype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityworktype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductioncharactertype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductioncharactertype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductiongenretype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductiongenretype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionorganitytype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionorganitytype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionproductiontype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionproductiontype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionworktype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionworktype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowcharactertype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowcharactertype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowgenretype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowgenretype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='entity_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
        migrations.AlterField(
            model_name='relationshoworganitytype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshoworganitytype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowproductiontype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowproductiontype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowshowtype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowshowtype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowworktype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowworktype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationurlurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationurlurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkcharactertype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkcharactertype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkgenretype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkgenretype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkurltype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkurltype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkworktype',
            name='inverted_name',
            field=models.CharField(help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkworktype',
            name='name',
            field=models.CharField(help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(help_text='Enter a name for the entity', max_length=200),
        ),
    ]
