# Generated by Django 2.2.6 on 2019-10-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityperson',
            old_name='full_name',
            new_name='sort_name',
        ),
    ]
