# Generated by Django 2.2.6 on 2019-10-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshowshowtype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the show - show relation type', max_length=200),
        ),
    ]
