# Generated by Django 2.2.6 on 2019-10-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191030_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationcharactercharactertype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharactergenretype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationcharacterurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationgenregenretype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationgenreurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganitycharactertype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganitygenretype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityorganitytype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationorganityworktype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductioncharactertype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductiongenretype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionorganitytype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionproductiontype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationproductionworktype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowcharactertype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowgenretype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshoworganitytype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowproductiontype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowshowtype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationshowworktype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationurlurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkcharactertype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkgenretype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkurltype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
        migrations.AlterField(
            model_name='relationworkworktype',
            name='name',
            field=models.CharField(default='relation type', help_text='A name for the x - y relation type', max_length=200),
        ),
    ]
