# Generated by Django 2.2.6 on 2019-10-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191030_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_a_name', models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True)),
                ('entity_b_name', models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='relationshowshow',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='relationshowshow',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='relationshowshow',
            name='show_a_name',
        ),
        migrations.RemoveField(
            model_name='relationshowshow',
            name='show_b_name',
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='show_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_show_a', to='catalog.EntityShow'),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='show_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_show_b', to='catalog.EntityShow'),
        ),
    ]
