# Generated by Django 2.2.6 on 2019-11-06 11:03

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191105_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationOrganityOrganityalias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_a_credited_as', models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True)),
                ('entity_b_credited_as', models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True)),
                ('relation_name', models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True)),
                ('begin_date', partial_date.fields.PartialDateField(blank=True, default=None, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, default=None, null=True)),
                ('highlighted_relation', models.BooleanField(blank=True, null=True)),
                ('inverted_relation', models.BooleanField(default=False)),
                ('context_of_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationorganityorganityalias_context_character', to='catalog.EntityCharacter')),
                ('context_of_organity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationorganityorganityalias_context_organity', to='catalog.EntityOrganity')),
                ('context_of_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationorganityorganityalias_context_production', to='catalog.EntityProduction')),
                ('context_of_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationorganityorganityalias_context_show', to='catalog.EntityShow')),
                ('context_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationorganityorganityalias_context_work', to='catalog.EntityWork')),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganityAlias')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganityAliasType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
