# Generated by Django 2.2.6 on 2019-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191030_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.RenameField(
            model_name='relationshowshow',
            old_name='show_a',
            new_name='entity_a',
        ),
        migrations.RenameField(
            model_name='relationshowshow',
            old_name='show_b',
            new_name='entity_b',
        ),
        migrations.RemoveField(
            model_name='relationshowproduction',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='relationshowproduction',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='relationshowproduction',
            name='production_name',
        ),
        migrations.RemoveField(
            model_name='relationshowproduction',
            name='show_name',
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
    ]
