# Generated by Django 2.2.6 on 2019-11-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_relationorganityorganityalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nl_be', help_text='Enter the abbrevation for the locale', max_length=10)),
                ('description', models.CharField(default='Dutch as spoken in Belgium', help_text='Describe the locale', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='RelationOrganityOrganityalias',
        ),
        migrations.AddField(
            model_name='entitygenrealias',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Locale'),
        ),
        migrations.AddField(
            model_name='entityorganityalias',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Locale'),
        ),
        migrations.AddField(
            model_name='entityworkalias',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Locale'),
        ),
    ]
