# Generated by Django 2.2.6 on 2019-10-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_relationvenuevenue_relationvenuevenuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationvenuevenue',
            name='venue_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationvenuevenue_venue_a', to='catalog.EntityVenue'),
        ),
        migrations.AlterField(
            model_name='relationvenuevenue',
            name='venue_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationvenuevenue_venue_b', to='catalog.EntityVenue'),
        ),
    ]
