# Generated by Django 2.2.6 on 2019-11-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191106_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='abbrevation',
            field=models.CharField(default='nl_be', help_text='Enter the abbrevation for the locale', max_length=10),
        ),
        migrations.AlterField(
            model_name='locale',
            name='name',
            field=models.CharField(default='Dutch (BE)', help_text='Enter the name of the locale', max_length=100),
        ),
    ]
