# Generated by Django 2.2.6 on 2019-11-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191106_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_character_str',
            field=models.CharField(blank=True, help_text='If there is a context of a character for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, help_text='If there is a context of an organity for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_production_str',
            field=models.CharField(blank=True, help_text='If there is a context of a production for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_show_str',
            field=models.CharField(blank=True, help_text='If there is a context of a show for this relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_work_str',
            field=models.CharField(blank=True, help_text='If there is a context of a work for this relation', max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='relationcharactercharacter',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationCharacterCharacterType'),
        ),
        migrations.RemoveField(
            model_name='relationcharactergenre',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationCharacterGenreType'),
        ),
        migrations.RemoveField(
            model_name='relationcharacterurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationCharacterUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationgenregenre',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationGenreGenreType'),
        ),
        migrations.RemoveField(
            model_name='relationgenreurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationGenreUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationorganitycharacter',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationOrganityCharacterType'),
        ),
        migrations.RemoveField(
            model_name='relationorganitygenre',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationOrganityGenreType'),
        ),
        migrations.RemoveField(
            model_name='relationorganityorganity',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationOrganityOrganityType'),
        ),
        migrations.RemoveField(
            model_name='relationorganityurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationOrganityUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationorganitywork',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationOrganityWorkType'),
        ),
        migrations.RemoveField(
            model_name='relationproductioncharacter',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationProductionCharacterType'),
        ),
        migrations.RemoveField(
            model_name='relationproductiongenre',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationProductionGenreType'),
        ),
        migrations.RemoveField(
            model_name='relationproductionorganity',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationProductionOrganityType'),
        ),
        migrations.RemoveField(
            model_name='relationproductionproduction',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationProductionProductionType'),
        ),
        migrations.RemoveField(
            model_name='relationproductionurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationProductionUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationproductionwork',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationProductionWorkType'),
        ),
        migrations.RemoveField(
            model_name='relationshowcharacter',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowCharacterType'),
        ),
        migrations.RemoveField(
            model_name='relationshowgenre',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowGenreType'),
        ),
        migrations.RemoveField(
            model_name='relationshoworganity',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowOrganityType'),
        ),
        migrations.RemoveField(
            model_name='relationshowproduction',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowProductionType'),
        ),
        migrations.RemoveField(
            model_name='relationshowshow',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowShowType'),
        ),
        migrations.RemoveField(
            model_name='relationshowurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationshowwork',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationShowWorkType'),
        ),
        migrations.RemoveField(
            model_name='relationurlurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationUrlUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationworkcharacter',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationWorkCharacterType'),
        ),
        migrations.RemoveField(
            model_name='relationworkgenre',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationWorkGenreType'),
        ),
        migrations.RemoveField(
            model_name='relationworkurl',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationWorkUrlType'),
        ),
        migrations.RemoveField(
            model_name='relationworkwork',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='relation_type',
            field=models.ManyToManyField(to='catalog.RelationWorkWorkType'),
        ),
    ]
