# Generated by Django 2.2.6 on 2019-10-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191026_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationVenueProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the venue - production relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationVenueProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, help_text='If venue was credited differently', max_length=200, null=True)),
                ('production_name', models.CharField(blank=True, help_text='If production was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityProduction')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationVenueProductionType')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityVenue')),
            ],
        ),
    ]
