# Generated by Django 2.2.6 on 2019-11-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191106_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityurl',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='entityurl',
            name='href',
        ),
        migrations.RemoveField(
            model_name='entityurl',
            name='sort_name',
        ),
        migrations.AlterField(
            model_name='entityurl',
            name='name',
            field=models.URLField(help_text='Enter the url'),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactercharacter',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre'),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharactergenre',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationcharacterurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenregenre',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationgenreurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityCharacter'),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre'),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityorganity',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityWork'),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityCharacter'),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductioncharacter',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre'),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductiongenre',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionproduction',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityWork'),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationproductionwork',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowcharacter',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowgenre',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshoworganity',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowproduction',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowshow',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshowwork',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationurlurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityCharacter'),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkcharacter',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='entity_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre'),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkgenre',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkurl',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='context_of_character_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='context_of_organity_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='context_of_production_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='context_of_show_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='context_of_work_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='entity_a_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='entity_b_credited_as',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationworkwork',
            name='relation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
