# Generated by Django 2.2.6 on 2019-10-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_relationvenueproduction_relationvenueproductiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationVenuePersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the venue - person relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationVenuePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, help_text='If venue was credited differently', max_length=200, null=True)),
                ('person_name', models.CharField(blank=True, help_text='If person was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityPerson')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationVenuePersonType')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityVenue')),
            ],
        ),
    ]
