# Generated by Django 2.2.6 on 2019-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191030_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='begin_date',
            field=models.DateField(blank=True, help_text='When did the relation start?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='end_date',
            field=models.DateField(blank=True, help_text='When did the relation end?', null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='entity_a_name',
            field=models.CharField(blank=True, help_text='If first entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='entity_b_name',
            field=models.CharField(blank=True, help_text='If second entity was credited differently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='relation_name',
            field=models.CharField(blank=True, help_text='A name for the relation', max_length=200, null=True),
        ),
    ]
