# Generated by Django 2.2.6 on 2019-11-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191109_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locale',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
    ]
