# Generated by Django 2.2.6 on 2019-10-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191030_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='highlighted_relation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
