# Generated by Django 2.2.6 on 2019-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191030_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationcharactercharactertype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationcharactergenretype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationcharacterurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationgenregenretype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationgenreurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganitycharactertype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganitygenretype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganityorganitytype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganityurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganityworktype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationproductioncharactertype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationproductiongenretype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationproductionorganitytype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationproductionproductiontype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationproductionurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationproductionworktype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshowcharactertype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshowgenretype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshoworganitytype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshowproductiontype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshowshowtype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshowurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshowworktype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationurlurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationworkcharactertype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationworkgenretype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationworkurltype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='inverted_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationworkworktype',
            name='inverted_name',
            field=models.CharField(default='inverted relation type', help_text='A name for the y - x relation type (inverted)', max_length=200),
        ),
    ]
