# Generated by Django 2.2.6 on 2019-10-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_relationvenueorganisation_relationvenueorganisationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProductionProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the production - production relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationProductionProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_a_name', models.CharField(blank=True, help_text='If first production was credited differently', max_length=200, null=True)),
                ('production_b_name', models.CharField(blank=True, help_text='If second production was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('production_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationproductionproduction_production_a', to='catalog.EntityProduction')),
                ('production_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationproductionproduction_production_b', to='catalog.EntityProduction')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationProductionProductionType')),
            ],
        ),
    ]
