# Generated by Django 2.2.6 on 2019-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20191031_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityshow',
            old_name='show_type',
            new_name='entity_type',
        ),
        migrations.RemoveField(
            model_name='entityproduction',
            name='disambiguation',
        ),
        migrations.AddField(
            model_name='entityshow',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
    ]
