# Generated by Django 2.2.6 on 2019-10-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_relationproductionproduction_relationproductionproductiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProductionPersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the production - person relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationProductionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(blank=True, help_text='If production was credited differently', max_length=200, null=True)),
                ('person_name', models.CharField(blank=True, help_text='If person was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityPerson')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityProduction')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationProductionPersonType')),
            ],
        ),
    ]
