# Generated by Django 2.2.6 on 2019-10-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_relationproductionperson_relationproductionpersontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationproductionperson',
            name='relation_str',
            field=models.CharField(blank=True, help_text='If relation is credited differently', max_length=200, null=True),
        ),
    ]
