# Generated by Django 2.2.6 on 2019-10-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191031_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='entitycharacter',
            old_name='character_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='entitycharacteralias',
            old_name='character',
            new_name='super_entity',
        ),
        migrations.RenameField(
            model_name='entitygenre',
            old_name='genre_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='entitygenrealias',
            old_name='genre',
            new_name='super_entity',
        ),
        migrations.RenameField(
            model_name='entityorganity',
            old_name='organity_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='entityorganityalias',
            old_name='organity',
            new_name='super_entity',
        ),
        migrations.RenameField(
            model_name='entityproduction',
            old_name='production_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='entityurl',
            old_name='url_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='entitywork',
            old_name='work_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='entityworkalias',
            old_name='work',
            new_name='super_entity',
        ),
        migrations.RemoveField(
            model_name='entitycharacteralias',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entitycharacteraliastype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entityworkaliastype',
            name='name',
        ),
        migrations.AddField(
            model_name='entitycharacter',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AddField(
            model_name='entitygenre',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entitygenre',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AddField(
            model_name='entityorganity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityorganity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityproduction',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityproduction',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AddField(
            model_name='entityshow',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AddField(
            model_name='entityurl',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityurl',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AddField(
            model_name='entitywork',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitycharacter',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitycharactertype',
            name='name',
            field=models.CharField(help_text='Enter a name for a show type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitygenre',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitygenrealias',
            name='name',
            field=models.CharField(help_text='Enter an alias for the organity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitygenrealiastype',
            name='name',
            field=models.CharField(help_text='A work alias type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitygenretype',
            name='name',
            field=models.CharField(help_text='Enter a name for a show type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityorganity',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityorganityaliastype',
            name='name',
            field=models.CharField(help_text='A work alias type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityorganitytype',
            name='name',
            field=models.CharField(help_text='Enter a name for a show type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityproduction',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityproduction',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Season'),
        ),
        migrations.AlterField(
            model_name='entityproductiontype',
            name='name',
            field=models.CharField(help_text='Enter a name for a show type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityshow',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityurl',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityurltype',
            name='name',
            field=models.CharField(help_text='Enter a name for a show type', max_length=200),
        ),
        migrations.AlterField(
            model_name='entitywork',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entitywork',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityworkalias',
            name='name',
            field=models.CharField(help_text='Enter an alias for the organity', max_length=200),
        ),
        migrations.AlterField(
            model_name='entityworktype',
            name='name',
            field=models.CharField(help_text='Enter a name for a show type', max_length=200),
        ),
        migrations.DeleteModel(
            name='EntitySeason',
        ),
    ]
