# Generated by Django 2.2.6 on 2019-11-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191110_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitywork',
            name='start_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
