# Generated by Django 2.2.6 on 2019-11-12 12:32

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_entitywork_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityshow',
            name='when_date',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
    ]
