# Generated by Django 2.2.6 on 2019-10-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_relationproductionperson_relation_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProductionOrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the production - organisation relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationProductionOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(blank=True, help_text='If production was credited differently', max_length=200, null=True)),
                ('organisation_name', models.CharField(blank=True, help_text='If organisation was credited differently', max_length=200, null=True)),
                ('relation_str', models.CharField(blank=True, help_text='If relation is credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganisation')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityProduction')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationProductionOrganisationType')),
            ],
        ),
    ]
