# Generated by Django 2.2.6 on 2019-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191031_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(default='not yet set', help_text='Enter a name for the entity', max_length=200),
        ),
    ]
