# Generated by Django 2.2.6 on 2019-10-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_relationproductionorganisation_relationproductionorganisationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationPersonPersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the person - person relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationPersonPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_a_name', models.CharField(blank=True, help_text='If first person was credited differently', max_length=200, null=True)),
                ('person_b_name', models.CharField(blank=True, help_text='If second person was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationpersonperson_person_a', to='catalog.EntityPerson')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationpersonperson_person_b', to='catalog.EntityPerson')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationPersonPersonType')),
            ],
        ),
    ]
