# Generated by Django 2.2.6 on 2019-10-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_season_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactercharacter_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactercharacter_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactercharacter_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactercharacter_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationcharactercharacter',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactercharacter_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactergenre_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactergenre_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactergenre_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactergenre_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationcharactergenre',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharactergenre_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharacterurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharacterurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharacterurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharacterurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationcharacterurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationcharacterurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenregenre_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenregenre_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenregenre_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenregenre_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationgenregenre',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenregenre_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenreurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenreurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenreurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenreurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationgenreurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationgenreurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitycharacter_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitycharacter_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitycharacter_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitycharacter_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationorganitycharacter',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitycharacter_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitygenre_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitygenre_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitygenre_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitygenre_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationorganitygenre',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitygenre_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityorganity_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityorganity_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityorganity_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityorganity_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationorganityorganity',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityorganity_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationorganityurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganityurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitywork_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitywork_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitywork_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitywork_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationorganitywork',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationorganitywork_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductioncharacter_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductioncharacter_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductioncharacter_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductioncharacter_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationproductioncharacter',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductioncharacter_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductiongenre_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductiongenre_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductiongenre_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductiongenre_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationproductiongenre',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductiongenre_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionorganity_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionorganity_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionorganity_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionorganity_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationproductionorganity',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionorganity_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionproduction_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionproduction_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionproduction_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionproduction_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationproductionproduction',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionproduction_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationproductionurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionwork_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionwork_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionwork_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionwork_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationproductionwork',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationproductionwork_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowcharacter_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowcharacter_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowcharacter_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowcharacter_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshowcharacter',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowcharacter_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowgenre_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowgenre_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowgenre_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowgenre_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshowgenre',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowgenre_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshoworganity_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshoworganity_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshoworganity_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshoworganity_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshoworganity',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshoworganity_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowproduction_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowproduction_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowproduction_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowproduction_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshowproduction',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowproduction_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshowshow',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowshow_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshowurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowwork_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowwork_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowwork_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowwork_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationshowwork',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationshowwork_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationurlurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationurlurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationurlurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationurlurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationurlurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationurlurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkcharacter_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkcharacter_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkcharacter_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkcharacter_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationworkcharacter',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkcharacter_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkgenre_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkgenre_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkgenre_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkgenre_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationworkgenre',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkgenre_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkurl_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkurl_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkurl_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkurl_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationworkurl',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkurl_context_work', to='catalog.EntityWork'),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkwork_context_character', to='catalog.EntityCharacter'),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_organity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkwork_context_organity', to='catalog.EntityOrganity'),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkwork_context_production', to='catalog.EntityProduction'),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkwork_context_show', to='catalog.EntityShow'),
        ),
        migrations.AddField(
            model_name='relationworkwork',
            name='context_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_relationworkwork_context_work', to='catalog.EntityWork'),
        ),
    ]
