# Generated by Django 2.2.6 on 2019-11-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_entityproductioncollection_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityproductioncollection',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
