# Generated by Django 2.2.6 on 2019-11-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_entityproductioncollection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityproductioncollection',
            name='name',
            field=models.CharField(blank=True, default='not named', max_length=200, null=True),
        ),
    ]
