# Generated by Django 2.2.6 on 2019-11-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20191031_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityorganity',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
