# Generated by Django 2.2.6 on 2019-10-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_relationpersonorganisation_relationpersonorganisationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationOrganisationOrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the organisation - organisation relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationOrganisationOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_a_name', models.CharField(blank=True, help_text='If first organisation was credited differently', max_length=200, null=True)),
                ('organisation_b_name', models.CharField(blank=True, help_text='If second organisation was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('organisation_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationorganisationorganisation_organisation_a', to='catalog.EntityOrganisation')),
                ('organisation_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationorganisationorganisation_organisation_b', to='catalog.EntityOrganisation')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationOrganisationOrganisationType')),
            ],
        ),
    ]
