# Generated by Django 2.2.6 on 2019-11-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20191115_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EntityProductionCollection',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
