# Generated by Django 2.2.6 on 2019-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20191101_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityorganity',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
