# Generated by Django 2.2.6 on 2019-10-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20191027_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitywork',
            old_name='work_types',
            new_name='work_type',
        ),
    ]
