# Generated by Django 2.2.6 on 2019-11-01 11:06

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20191101_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityorganity',
            name='end_date',
            field=partial_date.fields.PartialDateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entityorganity',
            name='start_date',
            field=partial_date.fields.PartialDateField(blank=True, default=None, null=True),
        ),
    ]
