# Generated by Django 2.2.6 on 2019-11-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20191101_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationorganitycharacter',
            name='entity_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
        migrations.AlterField(
            model_name='relationorganitygenre',
            name='entity_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
        migrations.AlterField(
            model_name='relationorganityurl',
            name='entity_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
        migrations.AlterField(
            model_name='relationorganitywork',
            name='entity_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
        migrations.AlterField(
            model_name='relationproductionorganity',
            name='entity_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityOrganity'),
        ),
    ]
