# Generated by Django 2.2.6 on 2019-10-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20191027_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the character', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityCharacterAliasType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A character alias type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityCharacterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for a character type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityCharacterAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an alias for the character', max_length=200)),
                ('alias_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityCharacterAliasType')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityCharacter')),
            ],
        ),
        migrations.AddField(
            model_name='entitycharacter',
            name='character_type',
            field=models.ManyToManyField(blank=True, to='catalog.EntityCharacterType'),
        ),
    ]
