# Generated by Django 2.2.6 on 2019-10-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_relationshowcharacter_relationshowcharactertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityGenreAliasType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A genre alias type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityGenreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for a genre type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntityGenreAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an alias for the genre', max_length=200)),
                ('alias_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenreAliasType')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre')),
            ],
        ),
        migrations.AddField(
            model_name='entitygenre',
            name='genre_type',
            field=models.ManyToManyField(blank=True, to='catalog.EntityGenreType'),
        ),
    ]
