# Generated by Django 2.2.6 on 2019-10-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_relationshowgenre_relationshowgenretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(help_text='Enter the url', max_length=200)),
                ('name', models.CharField(blank=True, help_text='Enter a name for the url', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityUrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for a url type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationShowUrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the show - url relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationShowUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(blank=True, help_text='If show was credited differently', max_length=200, null=True)),
                ('url_name', models.CharField(blank=True, help_text='If url was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationShowUrlType')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityShow')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityUrl')),
            ],
        ),
        migrations.AddField(
            model_name='entityurl',
            name='url_type',
            field=models.ManyToManyField(blank=True, to='catalog.EntityUrlType'),
        ),
    ]
