# Generated by Django 2.2.6 on 2019-10-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_relationvenuegenre_relationvenuegenretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationVenueUrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the venue - url relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationVenueUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, help_text='If venue was credited differently', max_length=200, null=True)),
                ('url_name', models.CharField(blank=True, help_text='If url was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationVenueUrlType')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityUrl')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityVenue')),
            ],
        ),
    ]
