# Generated by Django 2.2.6 on 2019-10-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_relationvenueurl_relationvenueurltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProductionWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the production - work relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationProductionWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(blank=True, help_text='If production was credited differently', max_length=200, null=True)),
                ('work_name', models.CharField(blank=True, help_text='If work was credited differently', max_length=200, null=True)),
                ('relation_str', models.CharField(blank=True, help_text='If relation is credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityProduction')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationProductionWorkType')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityWork')),
            ],
        ),
    ]
