# Generated by Django 2.2.6 on 2019-10-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_relationproductiongenre_relationproductiongenretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProductionUrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the production - url relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationProductionUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(blank=True, help_text='If production was credited differently', max_length=200, null=True)),
                ('url_name', models.CharField(blank=True, help_text='If url was credited differently', max_length=200, null=True)),
                ('relation_str', models.CharField(blank=True, help_text='If relation is credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityProduction')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationProductionUrlType')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityUrl')),
            ],
        ),
    ]
