# Generated by Django 2.2.6 on 2019-10-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_relationpersoncharacter_relationpersoncharactertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationPersonGenreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the person - genre relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationPersonGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, help_text='If person was credited differently', max_length=200, null=True)),
                ('genre_name', models.CharField(blank=True, help_text='If genre was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityPerson')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationPersonGenreType')),
            ],
        ),
    ]
