# Generated by Django 2.2.6 on 2019-10-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_relationworkurl_relationworkurltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationworkurl',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationWorkUrlType'),
        ),
    ]
