# Generated by Django 2.2.6 on 2019-10-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20191027_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationCharacterCharacterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the character - character relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationCharacterCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_a_name', models.CharField(blank=True, help_text='If first character was credited differently', max_length=200, null=True)),
                ('character_b_name', models.CharField(blank=True, help_text='If second character was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationcharactercharacter_character_a', to='catalog.EntityCharacter')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationcharactercharacter_character_b', to='catalog.EntityCharacter')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationCharacterCharacterType')),
            ],
        ),
    ]
