# Generated by Django 2.2.6 on 2019-10-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_relationcharactercharacter_relationcharactercharactertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationCharacterGenreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the character - genre relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationCharacterGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, help_text='If character was credited differently', max_length=200, null=True)),
                ('genre_name', models.CharField(blank=True, help_text='If genre was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityCharacter')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationCharacterGenreType')),
            ],
        ),
    ]
