# Generated by Django 2.2.6 on 2019-10-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_relationcharacterurl_relationcharacterurltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationGenreGenreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the genre - genre relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationGenreGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_a_name', models.CharField(blank=True, help_text='If first genre was credited differently', max_length=200, null=True)),
                ('genre_b_name', models.CharField(blank=True, help_text='If second genre was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('genre_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationgenregenre_genre_a', to='catalog.EntityGenre')),
                ('genre_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationgenregenre_genre_b', to='catalog.EntityGenre')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationGenreGenreType')),
            ],
        ),
    ]
