# Generated by Django 2.2.6 on 2019-10-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_relationgenregenre_relationgenregenretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationUrlUrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the url - url relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationUrlUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_a_name', models.CharField(blank=True, help_text='If first url was credited differently', max_length=200, null=True)),
                ('url_b_name', models.CharField(blank=True, help_text='If second url was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationUrlUrlType')),
                ('url_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationurlurl_url_a', to='catalog.EntityUrl')),
                ('url_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationurlurl_url_b', to='catalog.EntityUrl')),
            ],
        ),
    ]
