# Generated by Django 2.2.6 on 2019-10-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_relationurlurl_relationurlurltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationGenreUrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the genre - url relation type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationGenreUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, help_text='If genre was credited differently', max_length=200, null=True)),
                ('url_name', models.CharField(blank=True, help_text='If url was credited differently', max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, help_text='When did the relation start?', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When did the relation end?', null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityGenre')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.RelationGenreUrlType')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.EntityUrl')),
            ],
        ),
    ]
