# Generated by Django 2.2.6 on 2019-10-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_relationgenreurl_relationgenreurltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityshow',
            old_name='show_type',
            new_name='showtype',
        ),
    ]
