# Generated by Django 2.2.6 on 2019-10-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20191027_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityshow',
            old_name='showtype',
            new_name='show_type',
        ),
    ]
