# Generated by Django 2.2.6 on 2019-10-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20191027_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityperson',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='Some disambiguation information', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entityperson',
            name='sort_name',
            field=models.CharField(default='please provide a sort name', help_text='Representation of the name to sort on', max_length=200),
        ),
    ]
