# Generated by Django 2.2.6 on 2019-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_auto_20191027_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitycharacter',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityorganisation',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityorganisation',
            name='sort_name',
            field=models.CharField(default='not yet set', help_text='Sort on this name', max_length=200),
        ),
        migrations.AddField(
            model_name='entityproduction',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A disambiguation line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityvenue',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A Disambiguation Line', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entitywork',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='A Disambiguation Line', max_length=200, null=True),
        ),
    ]
